services:
  database:
    image: docker.io/library/postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Your_password123
      POSTGRES_DB: DesafioDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: DesafioTecnico.Api/Dockerfile
    image: localhost/desafiodotnet_api:latest
    depends_on:
      database:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=DesafioDB;Username=postgres;Password=Your_password123"
    ports:
      - "5000:5000"
    command: ["dotnet", "DesafioTecnico.Api.dll"]

  frontend:
    build: ./frontend
    image: localhost/desafiodotnet_frontend:latest
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - api

volumes:
  postgres-data:
